gift/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('user.urls',namespace='user')),
    url(r'^retailer/', include('retailer.urls',namespace='retailer')),
    url(r'^admin/', admin.site.urls),
]

retailer/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    #url(r'^user/$', views.user, name='test'),
    #url(r'^user/submit_data', views.sub, name='sub'),
]

user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.user, name='index'),
    url(r'^user/$', views.user, name='test'),
    url(r'^user/submit_data', views.sub, name='sub'),
]

retailer/models.py
from django.db import models
from django.core.validators import RegexValidator

class Data(models.Model):

    phone_checker=RegexValidator(r'^[7,8,9]{1}[0-9]{9}$','The given phone number does not exist in India')

    GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other'),
    )

    fname=models.CharField(max_length=31)
    lname=models.CharField(max_length=31)
    email=models.EmailField(max_length=31, unique=True)
    phone=models.IntegerField(unique=True, validators=[phone_checker])
    gender=models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
    bank_account_number=models.IntegerField()
    password=models.CharField(max_length=31)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Shortcomings(models.Model):


    priority_checker=RegexValidator(r'^[1,2,3,4,5]$','Rating must be between 1-5')
    priority = models.IntegerField(validators=[priority_checker])
    comment = models.CharField(max_length=127)
    review_holder = models.ForeignKey(Data, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class Products(models.Model):


    name = models.CharField(max_length=31)
    price=models.IntegerField()
    stock=models.IntegerField()
    manufacturig_time=models.IntegerField()
    delivery_time=models.IntegerField()
    description=models.CharField(max_length=1023)
    score=models.IntegerField()
    retailer= models.ForeignKey(Data, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Same_day(models.Model):
    product=models.ForeignKey(Products, on_delete=models.CASCADE)

class Packages(models.Model):
    combo_price=models.IntegerField()

class Packages_pack(models.Model):
    product=models.ForeignKey(Packages, on_delete=models.CASCADE)
    product=models.ForeignKey(Products, on_delete=models.CASCADE)

class Occasion(models.Model):
    submenu = models.CharField(max_length=15)

class Men(models.Model):
    submenu = models.CharField(max_length=15)

class Women(models.Model):
    submenu = models.CharField(max_length=15)

class Men_product(models.Model):
    submenu=models.ForeignKey(Men, on_delete=models.CASCADE)
    product=models.ForeignKey(Products, on_delete=models.CASCADE)

class Women_product(models.Model):
    submenu=models.ForeignKey(Women, on_delete=models.CASCADE)
    product=models.ForeignKey(Products, on_delete=models.CASCADE)

user/models.py
from django.db import models
from django.core.validators import RegexValidator
from retailer.models import Products

class Info(models.Model):

    phone_checker=RegexValidator(r'^[7,8,9]{1}[0-9]{9}$','The given phone number does not exist in India')

    GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other'),
    )

    fname=models.CharField(max_length=31)
    lname=models.CharField(max_length=31)
    email=models.EmailField(max_length=31, unique=True)
    phone=models.IntegerField( unique=True, validators=[phone_checker])
    gender=models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
    password=models.CharField(max_length=31)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



class Review(models.Model):
    ## Changes needed after creating product table
    REVIEW_CHOICES = (
    ('W', 'Website'),
    ('R', 'Retailer'),
    ('P', 'Product'),
    )

    rating_checker=RegexValidator(r'^[1,2,3,4,5]$','Rating must be between 1-5')
    comment=models.CharField(max_length=4095)
    rating = models.IntegerField(validators=[rating_checker])
    review_holder = models.CharField(max_length=1, choices=REVIEW_CHOICES, default='W')
    user = models.ForeignKey(Info, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class Cart(models.Model):

    user = models.ForeignKey(Info, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

retailer/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import Info
from django.db import models
from django.db import connection
import hashlib


def user(request):
    return render(request,'user/index.html',{})

def sub(request):

    user_data=Info(fname=request.POST['fname'], lname=request.POST['lname'], email=request.POST['email'], password=request.POST['password'])
    user_data.save()
    cursor=connection.cursor()
    key=str(user_data.id)+"69"
    hashed_key=hashlib.sha1(key.encode('utf-8')).hexdigest()
    cursor.execute('CREATE TABLE %s ( cart varchar(31) )'%hashed_key)


def cart(request):
    cursor=connection.cursor()
    cursor.execute("CREATE TABLE %s ( cart varchar(31) )"%request.POST['fname'])

user/templates/user/index.html
<!DOCTY+PE html>
<html>
   <head>
      <title>Hopscotch Giftery</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% load static %}
      <link href="{% static 'user/css/glyphicon.css' %}" rel="stylesheet">

        {% load static %}
      <link href="{% static 'user/css/HSbootstrap.css' %}" rel="stylesheet" type="text/css" media="all"/>

        {% load static %}
      <link href="{% static 'user/css/HS.css' %}" rel="stylesheet" type="text/css" media="all"/>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        {% load static %}
      <script src="{% static 'user/js/jquery-3.2.0.js' %}"></script>
   </head>
   <body>
     <div data-role="page">
       <div data-role="header" data-position="fixed">
         <div id="top-bar">
           <div class="row">
             <div class="span10">
               <form method="POST" class="search_form">
                  <input type="text" class="input-block-level search-query" Placeholder="Search...">
               </form>
             </div>
             <div class="span4">
               <div class="account pull-right">
                  <ul class="user-menu">
                     <button type="button" class="btnn">Login</button>
                     <a name="top"></a>
                     <button class="btnn"><span class="glyphicon glyphicon-shopping-cart"></span>Cart</button>
                  </ul>
               </div>
             </div>
           </div>
         </div>
      <!--dropdowns-->
         <div class="container">
           <div class="wrapper row2">
             <nav id="topnav">
               <div class="row">
                  <div class="col-md-1">

                      {% load static %}
                     <img src="{% static 'user/images/demologo.png' %}" height="200px" width="300px" />
                  </div>
                  <div class="col-md-9">
                     <ul class="clear">
                        <li>
                           <a class="drop" href="#" title="Same day">Same day <span class="glyphicon glyphicon-chevron-down"></span></a>
                           <ul>
                              <li><a href="#" title="1">1</a></li>
                              <li><a href="#" title="2">2</a></li>
                              <li><a href="#" title="3">3</a></li>
                              <li><a href="#" title="4">4</a></li>
                              <li class="last-child"><a href="#" title="5">5</a></li>
                           </ul>
                        </li>
                        <li>
                           <a class="drop" href="#" title="Handmade"> Handmade <span class="glyphicon glyphicon-chevron-down"></span></a>
                           <ul>
                              <li><a href="#" title="1">1</a></li>
                              <li><a href="#" title="2">2</a></li>
                              <li><a href="#" title="3">3</a></li>
                              <li><a href="#" title="4">4</a></li>
                              <li class="last-child"><a href="#" title="5">5</a></li>
                           </ul>
                        </li>
                        <li>
                           <a class="drop" href="#" title="Occasion"> Occasion <span class="glyphicon glyphicon-chevron-down"></span></a>
                           <ul>
                              <li><a href="#" title="1">1</a></li>
                              <li><a href="#" title="2">2</a></li>
                              <li><a href="#" title="3">3</a></li>
                              <li><a href="#" title="4">4</a></li>
                              <li class="last-child"><a href="#" title="5">5</a></li>
                           </ul>
                        </li>
                        <li>
                           <a class="drop" href="#" title="Relaion"> Relation <span class="glyphicon glyphicon-chevron-down"></span></a>
                           <ul>
                              <li><a href="#" title="1">1</a></li>
                              <li><a href="#" title="2">2</a></li>
                              <li><a href="#" title="3">3</a></li>
                              <li><a href="#" title="4">4</a></li>
                              <li class="last-child"><a href="#" title="5">5</a></li>
                           </ul>
                        </li>
                        <li>
                           <a class="drop" href="#" title="Package"> Package <span class="glyphicon glyphicon-chevron-down"></span></a>
                           <ul>
                              <li><a href="#" title="1">1</a></li>
                              <li><a href="#" title="2">2</a></li>
                              <li><a href="#" title="3">3</a></li>
                              <li><a href="#" title="4">4</a></li>
                              <li class="last-child"><a href="#" title="5">5</a></li>
                           </ul>
                        </li>
                        <li class="last-child"><a href="#" title="Personal Assistance"><span class="glyphicon glyphicon-user"></span> Personal Assistance</a></li>
                     </ul>
                  </div>
               </div>
             </nav>
           </div>
         </div>
       </div>
      <!--slider-->
       <div class="Hs-content Hs-display-container">
         <div class="mySlides fade">

                   {% load static %}
            <img src="{% static 'user/images/1.jpg' %}" style="width:100%">
         </div>
         <div class="mySlides fade">

                   {% load static %}
            <img src="{% static 'user/images/2.jpg' %}" style="width:100%">
         </div>
         <div class="mySlides fade">

                   {% load static %}
            <img src="{% static 'user/images/3.jpg' %}" style="width:100%">
         </div>
         <div class="mySlides fade">

                   {% load static %}
            <img src="{% static 'user/images/4.jpg' %}" style="width:100%">
         </div>
         <div class="mySlides fade">

                   {% load static %}
            <img src="{% static 'user/images/6.jpg' %}" style="width:100%">
         </div>
         <button class="Hs-button Hs-black Hs-display-left btnn" onclick="plusDivs(-1)">&#10094;</button>
         <button class="Hs-button Hs-black Hs-display-right btnn" onclick="plusDivs(1)">&#10095;</button>
       </div>
       <div class="row">
         <div class="col-ld-4 textt">Trending this month</div>
         <div class="col-ld-4 textb">Trending this month</div>
         <div class="col-ld-4 textt">Trending this month</div>
         <div class="col-ld-4 textb">Trending this month</div>
       </div>
       <div class="row">
         <div class="col-ld-4 textb">Trending this month</div>
         <div class="col-ld-4 textt">Trending this month</div>
         <div class="col-ld-4 textb">Trending this month</div>
         <div class="col-ld-4 textt">Trending this month</div>
       </div>
       <div class="foot">
         <a href="#top"><button class="btn-top">Back to top</button></a>
      <!--
         <div class="slider1">
           <div class="slide"><img src="images/1.jpg"/></div>
           <div class="slide"><img src="images/2.jpg"/></div>
           <div class="slide"><img src="images/3.jpg"/></div>
           <div class="slide"><img src="images/4.jpg"/></div>
         </div>
         -->
         <div class="container">
           <div class="row2" >
             <div class="span3 col-xs-4 foots">
               <h3>Get to know us</h3>
               <ul class="nospace">
                  <li><a hre=#>About us</a></li>
                  <li><a hre=#>Contact Us</a></li>
                  <li><a hre=#>Blog</a></li>
                  <li><a hre=#>Stores</a></li>
               </ul>
             </div>
             <div class="span5 col-xs-4 foots">
               <h3>Help</h3>
               <ul class="nospace last2">
                  <li><a hre=#>Payments</a></li>
                  <li><a hre=#>Cancellation & Return</a></li>
                  <li><a hre=#>FAQ</a></li>
               </ul></div>
               <div class="span6 col-xs-4 foots">
                 <h3>Business</h3>
                 <ul class="nospace last2">
                   <li><a hre=#>Partner with HS</a></li>
                 </ul>
               </div>
             </div>
             <div style="display: block; clear: both;">
               <h2 style="color: white;">Follow us on:
                 <div id="social">
                     <a class="facebookBtn smGlobalBtn" href="#" ></a>
                     <a class="twitterBtn smGlobalBtn" href="#" ></a>
                     <a class="googleplusBtn smGlobalBtn" href="#" ></a>
                     <a class="linkedinBtn smGlobalBtn" href="#" ></a>
                     <a class="pinterestBtn smGlobalBtn" href="#" ></a>
                     <a class="tumblrBtn smGlobalBtn" href="#" ></a>
                     <a class="rssBtn smGlobalBtn" href="#" ></a>
                 </div>
               </h2>
             </div>
           </div>
         </div>
       </div>

       <script type="text/javascript">
         /*top*/
         var slideIndex = 0;
         showSlides();

         function showSlides() {
             var i;
             var slides = document.getElementsByClassName("mySlides");
             for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
         //    slides[slideIndex-1].style.z-index=1;
             }
             slideIndex++;
             if (slideIndex> slides.length) {slideIndex = 1}
             slides[slideIndex-1].style.display = "block";
             setTimeout(showSlides, 2000); // Change image every 2 seconds
         }

         function plusDivs(n) {
             showDivs(slideIndex += n);
         }

         function showDivs(n) {
             var i;
             var x = document.getElementsByClassName("mySlides");
             if (n > x.length) {slideIndex = 1}
             if (n < 1) {slideIndex = x.length} ;
             for (i = 0; i < x.length; i++) {
                 x[i].style.display = "none";
             }
             x[slideIndex-1].style.display = "block";
         }

      </script>
   </body>
</html>

user/templates/user/login.html
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Sign-Up/Login Form</title>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  {% load static %}
  <link rel="stylesheet" href="{% static 'user/css/style.css' %}">


</head>

<body>
  <div class="form">

      <ul class="tab-group">
        <li class="tab active"><a href="#signup">Sign Up</a></li>
        <li class="tab"><a href="#login">Log In</a></li>
      </ul>

      <div class="tab-content">
        <div id="signup">
          <h1>Sign Up for Free</h1>

          <form action="{% url 'user:sub' %}"  method="post">
       {% csrf_token %}
          <div class="top-row">
            <div class="field-wrap">
              <label>
                First Name<span class="req">*</span>
              </label>
              <input type="text" required autocomplete="off" name="fname"/>
            </div>

            <div class="field-wrap">
              <label>
                Last Name<span class="req">*</span>
              </label>
              <input type="text"required autocomplete="off" name="lname"/>
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off" name="email"/>
          </div>

          <div class="field-wrap">
            <label>
              Set A Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off" name="password"/>
          </div>

          <button type="submit" class="button button-block"/>Get Started</button>

          </form>

        </div>

        <div id="login">
          <h1>Welcome Back!</h1>

          <form action="/" method="post">

            <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>

          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>

          <p class="forgot"><a href="#">Forgot Password?</a></p>

          <button class="button button-block"/>Log In</button>

          </form>

        </div>

      </div><!-- tab-content -->

</div> <!-- /form -->
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
{% load static %}
    <script src="{% static 'user/js/index.js' %}"></script>

</body>
</html>